apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: proxy-client-SERVICE_NAME
  name: proxy-client-SERVICE_NAME
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8081
  selector:
    run: SERVICE_SELECTOR
  type: NodePort