apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: PROXY_DEPLOYMENT_NAME
  name: PROXY_DEPLOYMENT_NAME
spec:
  replicas: 1
  selector:
    matchLabels:
      run: PROXY_DEPLOYMENT_NAME
  template:
    metadata:
      labels:
        run: PROXY_DEPLOYMENT_NAME
    spec:
      containers:
        - env:
            - name: SERVICE_NAME
              value: "SERVICE_NAME_VALUE"
            - name: SERVICE_HOST
              value: "SERVICE_HOST_VALUE"
            - name: SERVICE_PORT
              value: "SERVICE_PORT_VALUE"
            - name: SERVICE_SSL
              value: "SERVICE_SSL_VALUE"
            - name: CLIENT_API_PORT
              value: "8081"
          image: docker.io/io.quarkus/quarkus-devspace-proxy:QUARKUS_VERSION
          imagePullPolicy: IfNotPresent
          name: PROXY_DEPLOYMENT_NAME
          ports:
            - containerPort: 8080
              name: proxy-http
              protocol: TCP
            - containerPort: 8081
              name: client-http
              protocol: TCP
