apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: SERVICE_NAME
  name: SERVICE_NAME
spec:
  ports:
    - name: http
      port: 80
      nodePort: 30963
      protocol: TCP
      targetPort: 8080
  selector:
    run: SERVICE_SELECTOR
  type: NodePort